# Generated by Django 2.2.2 on 2019-07-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0007_auto_20190710_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, '删除'), (1, '正常')], default=1, verbose_name='状态'),
        ),
    ]
