# Generated by Django 2.2.2 on 2019-06-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190620_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.PositiveIntegerField(choices=[(2, '草稿'), (1, '正常'), (0, '删除')], default=1, verbose_name='状态'),
        ),
    ]
