# Generated by Django 2.2.2 on 2019-06-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190626_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_html',
            field=models.TextField(blank=True, editable=False, verbose_name='正文HTML代码'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.PositiveIntegerField(choices=[(2, '草稿'), (0, '删除'), (1, '正常')], default=1, verbose_name='状态'),
        ),
    ]
