# Generated by Django 2.2.2 on 2019-07-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190627_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_toc',
            field=models.TextField(blank=True, editable=False, verbose_name='文章目录'),
        ),
    ]
