# Generated by Django 2.2.2 on 2019-07-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190708_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, '删除'), (2, '草稿'), (1, '正常')], default=1, verbose_name='状态'),
        ),
    ]
