# Generated by Django 2.2.2 on 2019-07-13 14:14

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190711_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_pic',
            field=imagekit.models.fields.ProcessedImageField(default='article_pic/default.png', upload_to='article_pic/%Y/%m/%d', verbose_name='文章配图'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, '删除'), (2, '草稿'), (1, '正常')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, '删除'), (1, '正常')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, '删除'), (1, '正常')], default=1, verbose_name='状态'),
        ),
    ]
