# Generated by Django 2.2.2 on 2019-07-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190713_2214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['is_top', '-id'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AddField(
            model_name='article',
            name='is_top',
            field=models.PositiveIntegerField(choices=[(2, '普通栏'), (1, '置顶栏'), (0, '海报栏')], default=2, verbose_name='置顶'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, '正常'), (2, '草稿'), (0, '删除')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, '正常'), (0, '删除')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, '正常'), (0, '删除')], default=1, verbose_name='状态'),
        ),
    ]
